package com.ftn.sbnz.kjar;

import com.ftn.sbnz.model.SimptomFakt;
import com.ftn.sbnz.model.KomponentaFakt;
import com.ftn.sbnz.model.KomponentaFakt.TipKomponente;
import com.ftn.sbnz.model.KvarFakt;
import com.ftn.sbnz.model.KvarFakt.TipKvara;

// Rucno definisano - zahteva dva istovremena uslova na SimptomFakt (RPM ok + temp visoka)
rule "Nivo2 - Istrosena termalna pasta"
    when
        $komp : KomponentaFakt(tipKomponente == TipKomponente.COOLING)
        $s : SimptomFakt(rpmVentilator >= 500, temperaturaCPU > 90)
        not KvarFakt(tipKvara == TipKvara.ISTROSENA_TERMALNA_PASTA)
    then
        insert(new KvarFakt(TipKvara.ISTROSENA_TERMALNA_PASTA, $komp));
        System.out.println("Nivo 2 (manual): ISTROSENA_TERMALNA_PASTA");
end
