package com.ftn.sbnz.kjar;

import com.ftn.sbnz.model.KvarFakt;
import com.ftn.sbnz.model.KvarFakt.TipKvara;
import com.ftn.sbnz.model.DijagnozaFakt;
import com.ftn.sbnz.model.DijagnozaFakt.Ozbiljnost;
import com.ftn.sbnz.model.SimptomFakt;

// Rucno definisano - ozbiljnost zavisi od konkretne vrednosti temperature GPU
rule "Nivo3 - Dijagnoza pregrevanje GPU kriticno"
    when
        $k : KvarFakt(tipKvara == TipKvara.PREGREVANJE_GPU)
        SimptomFakt(temperaturaGPU > 100)
        not DijagnozaFakt(kvar == $k)
    then
        insert(new DijagnozaFakt($k, Ozbiljnost.KRITICNO, "Odmah iskljuciti racunar. Proveriti GPU ventilator i termopaste."));
        System.out.println("Nivo 3 (manual): KRITICNO - PREGREVANJE_GPU");
end

// Rucno definisano - ozbiljnost zavisi od konkretne vrednosti temperature GPU
rule "Nivo3 - Dijagnoza pregrevanje GPU upozorenje"
    when
        $k : KvarFakt(tipKvara == TipKvara.PREGREVANJE_GPU)
        SimptomFakt(temperaturaGPU <= 100)
        not DijagnozaFakt(kvar == $k)
    then
        insert(new DijagnozaFakt($k, Ozbiljnost.UPOZORENJE, "Pratiti temperaturu GPU-a. Proveriti ventilaciju kucista."));
        System.out.println("Nivo 3 (manual): UPOZORENJE - PREGREVANJE_GPU");
end
