package com.ftn.sbnz.kjar;

import com.ftn.sbnz.model.SimptomFakt;
import com.ftn.sbnz.model.KomponentaFakt;
import com.ftn.sbnz.model.KomponentaFakt.TipKomponente;
import com.ftn.sbnz.model.KvarFakt;
import com.ftn.sbnz.model.KvarFakt.TipKvara;

// Rucno definisano - zahteva dva istovremena uslova na SimptomFakt (RPM ok + temp visoka)
rule "Nivo2 - Istrosena termalna pasta"
    when
        $komp : KomponentaFakt(tipKomponente == TipKomponente.COOLING)
        $s : SimptomFakt(rpmCPUVentilator >= 500, temperaturaCPU > 90)
        not KvarFakt(tipKvara == TipKvara.ISTROSENA_TERMALNA_PASTA)
    then
        insert(new KvarFakt(TipKvara.ISTROSENA_TERMALNA_PASTA, $komp));
        System.out.println("Nivo 2 (manual): ISTROSENA_TERMALNA_PASTA");
end

// Rucno definisano - zahteva istovremenu proveru temperature i opterecenja CPU
rule "Nivo2 - Pregrevanje CPU pod opterecenjem"
    when
        $komp : KomponentaFakt(tipKomponente == TipKomponente.CPU)
        $s : SimptomFakt(temperaturaCPU > 90, cpuUtilizacija > 90)
        not KvarFakt(tipKvara == TipKvara.PREGREVANJE_CPU)
    then
        insert(new KvarFakt(TipKvara.PREGREVANJE_CPU, $komp));
        System.out.println("Nivo 2 (manual): PREGREVANJE_CPU");
end
